# -*- coding: utf-8 -*-
"""Turkish translations for every GNN theme string."""

PLURALS = {
    '%1$s result for “%2$s”': (
        '“%2$s” için %1$s sonuç',
        '“%2$s” için %1$s sonuç',
    ),
    '%d min read': ('%d dk okuma', '%d dk okuma'),
    '%s article': ('%s yazı', '%s yazı'),
    '%s article in this archive.': (
        'Bu arşivde %s yazı var.',
        'Bu arşivde %s yazı var.',
    ),
    '%s comment': ('%s yorum', '%s yorum'),
}

TRANSLATIONS = {
    # --- Elementor Saved Templates library ---
    'Elementor templates': 'Elementor şablonları',
    'Elementor templates rebuilt.': 'Elementor şablonları yeniden oluşturuldu.',
    "GNN's designed sections as Elementor Saved Templates (Templates → Insert Template in the editor). Rebuild after changing the accent color so the templates match.":
        'GNN’in tasarlanmış bölümleri Elementor Kayıtlı Şablonlar olarak (editörde Şablonlar → Şablon Ekle). Vurgu rengini değiştirdikten sonra şablonların eşleşmesi için yeniden oluşturun.',
    'Rebuild Elementor templates': 'Elementor şablonlarını yeniden oluştur',
    'Sample title': 'Örnek başlık',
    'Add your introductory copy here. Describe the feature, product or story you want to highlight in a couple of short sentences.':
        'Giriş metninizi buraya ekleyin. Öne çıkarmak istediğiniz özelliği, ürünü ya da hikayeyi birkaç kısa cümleyle anlatın.',
    'Learn more': 'Daha fazla bilgi',
    'Etcetera': 'Ve diğerleri',
    'About the event': 'Etkinlik hakkında',
    'Held over a weekend, the event is structured around a series of exhibitions, workshops, and panel discussions. Replace this copy with your own.':
        'Bir hafta sonu boyunca süren etkinlik; sergiler, atölyeler ve panel tartışmalarından oluşuyor. Bu metni kendi içeriğinizle değiştirin.',
    'Frequently Asked Questions': 'Sıkça Sorulan Sorular',
    'Question one goes here?': 'Birinci soru buraya gelir?',
    'Question two goes here?': 'İkinci soru buraya gelir?',
    'Question three goes here?': 'Üçüncü soru buraya gelir?',
    'Question four goes here?': 'Dördüncü soru buraya gelir?',
    'Answer the question here. Replace this placeholder text with your own content.':
        'Cevabı buraya yazın. Bu örnek metni kendi içeriğinizle değiştirin.',
    'Got questions? Feel free to reach out.': 'Sorularınız mı var? Bize ulaşmaktan çekinmeyin.',
    'hello!': 'merhaba!',
    'Big bold headline': 'Büyük kalın başlık',
    '— second line': '— ikinci satır',
    'Add a short supporting paragraph here to describe the offer, product or story. Replace with your own copy.':
        'Teklifi, ürünü ya da hikayeyi anlatan kısa bir destekleyici paragrafı buraya ekleyin. Kendi metninizle değiştirin.',
    'BRAND.': 'MARKA.',
    'A new collection': 'Yeni bir koleksiyon',
    'Learn More →': 'Daha Fazla Bilgi →',
    'A bold headline goes here': 'Kalın bir başlık buraya gelir',
    'Explore': 'Keşfet',
    'A centered bold headline goes here': 'Ortalanmış kalın bir başlık buraya gelir',
    'Case study ↗': 'Örnek olay incelemesi ↗',
    'Open spaces': 'Açık alanlar',
    'Headline.': 'Başlık.',
    'Add a short, evocative introduction here. Replace this placeholder with your own copy describing the section, product or story.':
        'Etkileyici kısa bir giriş buraya ekleyin. Bu örnek metni bölümü, ürünü ya da hikayeyi anlatan kendi içeriğinizle değiştirin.',
    # --- Faz C/D: CPT slider, badges ---
    'Add New Slide': 'Yeni Slayt Ekle',
    'Add Slide': 'Slayt Ekle',
    'All Slides': 'Tüm Slaytlar',
    'Edit Slide': 'Slaytı Düzenle',
    'No slides yet.': 'Henüz slayt yok.',
    'Set background image': 'Arka plan görseli seç',
    'Slide Details': 'Slayt Ayrıntıları',
    'Hero slider': 'Hero slider',
    'Slides are managed under GNN Slider in the admin menu (unlimited slides).': 'Slaytlar yönetim menüsündeki GNN Slider bölümünden yönetilir (sınırsız slayt).',
    'Full-height slider (fills the screen below the header)': 'Tam yükseklik slider (üst bölümün altında ekranı kaplar)',
    'Set the standard background via the Featured Image box. The 2× image below is optional (used on Retina/high-DPI screens).': 'Standart arka planı Öne Çıkan Görsel kutusundan ayarlayın. Aşağıdaki 2× görsel isteğe bağlıdır (Retina / yüksek yoğunluklu ekranlarda kullanılır).',
    'Image fit': 'Görsel sığdırma',
    'Cover (fill, cropped)': 'Kapla (doldur, kırpılmış)',
    'Contain (fit, no crop)': 'Sığdır (kırpmadan)',
    'Cover — top': 'Kapla — üst',
    'Cover — bottom': 'Kapla — alt',
    'Cover — centered': 'Kapla — ortalı',
    'Slide order: set the "Order" field under Page Attributes (lower = earlier). An empty title hides the slide from the front page.': 'Slayt sırası: Sayfa Öznitelikleri altındaki "Sıra" alanını ayarlayın (küçük = önce). Boş başlık slaytı ön sayfadan gizler.',
    'Badge (e.g. New, Hot, Sale)': 'Rozet (ör. Yeni, Popüler, İndirim)',
    'Footer logo max height (px)': 'Alt bölüm logosu en fazla yükseklik (px)',
    'Controls logo height while preserving aspect ratio (default: 40px). Very wide banner-style logos may render slightly shorter if the footer column is narrow.':
        'En-boy oranını koruyarak logo yüksekliğini kontrol eder (varsayılan: 40px). Çok geniş, afiş tipi logolar, alt bölüm sütunu darsa biraz daha kısa görünebilir.',
    'HTML tags allowed (e.g. <a>, <br>, <strong>, <span>). Leave empty to use the site tagline.': 'HTML etiketlerine izin verilir (ör. <a>, <br>, <strong>, <span>). Site sloganını kullanmak için boş bırakın.',
    'Top bar background color': 'Üst çubuk zemin rengi',
    'Top bar text color': 'Üst çubuk metin rengi',
    'Matches the theme by default; pick a color to override.': 'Varsayılan olarak temayla eşleşir; geçersiz kılmak için bir renk seçin.',
    # --- Faz B: header/footer/404 wiring ---
    'Footer logo — light mode (1×)': 'Alt bölüm logosu — açık mod (1×)',
    'Footer logo — light mode (2× retina)': 'Alt bölüm logosu — açık mod (2× retina)',
    'Footer logo — dark mode (1×)': 'Alt bölüm logosu — koyu mod (1×)',
    'Footer logo — dark mode (2× retina)': 'Alt bölüm logosu — koyu mod (2× retina)',
    'Header Left (centered layout)': 'Üst Bölüm Sol (ortalı düzen)',
    'Header Right (centered layout)': 'Üst Bölüm Sağ (ortalı düzen)',
    'Header left': 'Üst bölüm sol',
    'Header right': 'Üst bölüm sağ',
    'Mobile navigation': 'Mobil gezinme',
    'Scroll to top': 'Yukarı çık',
    'Theme': 'Tema',
    'Slider': 'Slider',
    'We are performing scheduled maintenance. Please check back soon.': 'Planlı bakım çalışması yapıyoruz. Lütfen kısa süre sonra tekrar bakın.',
    # --- Panel (Faz A) + pattern titles ---
    'Global': 'Genel',
    'Header layout': 'Üst bölüm düzeni',
    'Layout': 'Düzen',
    'Menu alignment': 'Menü hizalama',
    'Center': 'Orta',
    'Standard (logo left, menu right)': 'Standart (logo solda, menü sağda)',
    'Centered (logo center, split menus)': 'Ortalı (logo ortada, bölünmüş menüler)',
    'Centered layout uses the Header Left and Header Right menu locations.': 'Ortalı düzen, Üst Bölüm Sol ve Üst Bölüm Sağ menü konumlarını kullanır.',
    'Interactions': 'Etkileşimler',
    'Smooth scroll for anchor links': 'Çapa bağlantıları için yumuşak kaydırma',
    'Show the “Scroll to top” button': '“Yukarı çık” butonunu göster',
    'Scroll-in animations for blocks/images': 'Bloklar/görseller için kaydırma animasyonları',
    'Adds reveal-on-scroll to elements with the gnn-anim class (respects reduced-motion).': 'gnn-anim sınıflı öğelere kaydırınca beliren efekt ekler (reduced-motion desteği dahil).',
    'Top loading progress bar': 'Üstte yükleme ilerleme çubuğu',
    'Full-screen loading overlay': 'Tam ekran yükleme katmanı',
    'Maintenance / Coming soon': 'Bakım / Çok yakında',
    'Enable maintenance mode (logged-out visitors only)': 'Bakım modunu etkinleştir (yalnız oturum açmamış ziyaretçiler)',
    'Maintenance message': 'Bakım mesajı',
    'Show the search icon': 'Arama ikonunu göster',
    'Logo max height — desktop (px)': 'Logo en fazla yükseklik — masaüstü (px)',
    'Logo max height — mobile (px)': 'Logo en fazla yükseklik — mobil (px)',
    'Mobile bottom app dock (≤600px)': 'Mobil alt uygulama çubuğu (≤600px)',
    'Top bar': 'Üst çubuk',
    'Enable the top announcement bar': 'Üst duyuru çubuğunu etkinleştir',
    'Announcement text': 'Duyuru metni',
    'Email': 'E-posta',
    'Phone': 'Telefon',
    'Footer': 'Alt Bölüm',
    'Footer brand': 'Alt bölüm markası',
    'Text (site title)': 'Metin (site başlığı)',
    'Image logo': 'Görsel logo',
    'Image + text': 'Görsel + metin',
    'Hide': 'Gizle',
    'Footer logo (1×)': 'Alt bölüm logosu (1×)',
    'Footer logo (2× retina)': 'Alt bölüm logosu (2× retina)',
    'Footer logo width (px)': 'Alt bölüm logo genişliği (px)',
    'Footer tagline': 'Alt bölüm sloganı',
    'Leave empty to use the site tagline.': 'Site sloganını kullanmak için boş bırakın.',
    'Footer menu alignment': 'Alt bölüm menü hizalama',
    'Pages Layout': 'Sayfa Düzeni',
    'Default sidebar position': 'Varsayılan kenar çubuğu konumu',
    '404 page': '404 sayfası',
    '404 title': '404 başlığı',
    '404 description': '404 açıklaması',
    'Show a search box on the 404 page': '404 sayfasında arama kutusu göster',
    '“Back to home” button text': '“Ana sayfaya dön” buton metni',
    '404 image': '404 görseli',
    'Colors': 'Renkler',
    'Typography': 'Tipografi',
    'The theme ships self-hosted Space Grotesk (headings) and Manrope (body). Font controls are managed in theme.json; per-option font settings can be added here.': 'Tema, kendi barındırılan Space Grotesk (başlıklar) ve Manrope (gövde) fontlarıyla gelir. Font kontrolleri theme.json’dan yönetilir; opsiyon bazlı font ayarları buraya eklenebilir.',
    'Icons': 'İkonlar',
    'The theme uses inline SVG icons. Icon management options appear here as they are added.': 'Tema satır içi SVG ikonlar kullanır. İkon yönetim seçenekleri eklendikçe burada görünür.',
    'Advanced': 'Gelişmiş',
    'Export settings': 'Ayarları dışa aktar',
    'Download all GNN Theme settings as a JSON file for backup or transfer.': 'Tüm GNN Tema ayarlarını yedek veya aktarım için JSON dosyası olarak indirin.',
    'Export JSON': 'JSON’a Aktar',
    'Import settings': 'Ayarları içe aktar',
    'Upload a previously exported GNN settings JSON file.': 'Daha önce dışa aktarılmış bir GNN ayar JSON dosyası yükleyin.',
    'Import JSON': 'JSON İçe Aktar',
    'Reset settings': 'Ayarları sıfırla',
    'Restore all GNN Theme settings to their defaults. This cannot be undone.': 'Tüm GNN Tema ayarlarını varsayılana döndürür. Bu işlem geri alınamaz.',
    'Reset to defaults': 'Varsayılana sıfırla',
    'Reset all GNN Theme settings to defaults?': 'Tüm GNN Tema ayarları varsayılana sıfırlansın mı?',
    'Permission denied.': 'İzin reddedildi.',
    'Settings imported successfully.': 'Ayarlar başarıyla içe aktarıldı.',
    'Import failed: the file is not a valid GNN settings export.': 'İçe aktarma başarısız: dosya geçerli bir GNN ayar dışa aktarımı değil.',
    'Settings reset to defaults.': 'Ayarlar varsayılana sıfırlandı.',
    # --- Pattern titles ---
    'Cover: poster left, text right': 'Kapak: solda afiş, sağda metin',
    'Two-tone background, centered image': 'İki tonlu arka plan, ortalanmış görsel',
    'Heading & paragraph with image': 'Başlık + paragraf, görselli',
    'FAQs': 'Sıkça Sorulan Sorular',
    'Contact with social links': 'Sosyal bağlantılı iletişim',
    'Dark banner, top-left heading': 'Koyu afiş, sol üst başlık',
    'Bold heading, paragraph & button': 'Kalın başlık, paragraf ve düğme',
    'Headline with links, gradient background': 'Bağlantılı başlık, degrade arka plan',
    'Cover: heading & button (left)': 'Kapak: başlık ve düğme (sol)',
    'Cover: heading & button (centered)': 'Kapak: başlık ve düğme (orta)',
    'Media & text (image left)': 'Görsel ve metin (solda görsel)',
    'Media & text (image right)': 'Görsel ve metin (sağda görsel)',
    'Large header over cover (left text)': 'Kapak üzerinde büyük başlık (sol metin)',
    'Two images side by side': 'Yan yana iki görsel',
    'Accent color': 'Vurgu rengi',
    'Add to cart': 'Sepete ekle',
    'After <body> HTML': '<body> sonrası HTML',
    'Appears in the footer widget area.': 'Footer bileşen alanında görünür.',
    'Appears on archives and pages with a sidebar.': 'Arşivlerde ve kenar çubuklu sayfalarda görünür.',
    'Archive': 'Arşiv',
    'Author': 'Yazar',
    'Autoplay (5s)': 'Otomatik oynatma (5 sn)',
    'Back to Home': 'Ana Sayfaya Dön',
    'Blog': 'Blog',
    'Blog & Shop': 'Blog ve Mağaza',
    'Boxed (max 1200px)': 'Kutulu (maks 1200px)',
    'Right Sidebar': 'Sağ Kenar Çubuğu',
    'Left Sidebar': 'Sol Kenar Çubuğu',
    'Blank Canvas (no header/footer)': 'Boş Tuval (başlık/altbilgi yok)',
    'Brand': 'Marka',
    'Breadcrumb': 'İçerik yolu',
    'Call-to-action band': 'Eylem çağrısı bandı',
    'Cover — gradient text': 'Kapak — degrade metin',
    'Cart': 'Sepet',
    'Category': 'Kategori',
    'Check back soon — new content is on the way.': 'Yakında tekrar bakın — yeni içerik yolda.',
    'Comments are closed.': 'Yorumlar kapalı.',
    'Contact': 'İletişim',
    'Custom CSS': 'Özel CSS',
    'Custom Code': 'Özel Kod',
    'Custom JavaScript — footer': 'Özel JavaScript — footer',
    'Custom JavaScript — head': 'Özel JavaScript — head',
    'Custom script fields were not saved: your account lacks the unfiltered_html capability.':
        'Özel script alanları kaydedilmedi: hesabınızda unfiltered_html yetkisi yok.',
    'Dark': 'Koyu',
    'Default mode': 'Varsayılan mod',
    'Disable the emoji script': 'Emoji script’ini devre dışı bırak',
    'Enterprise clients': 'Kurumsal müşteri',
    'Events analyzed daily': 'Günlük analiz edilen olay',
    'Excerpt length (words)': 'Özet uzunluğu (kelime)',
    'Extra <head> HTML (meta/verification tags)': 'Ek <head> HTML (meta/doğrulama etiketleri)',
    'Favicon (site icon, 512×512)': 'Favicon (site simgesi, 512×512)',
    'Feature band (media + bullets)': 'Özellik bandı (görsel + maddeler)',
    'Feature description goes here.': 'Özellik açıklaması buraya gelir.',
    'Feature title': 'Özellik başlığı',
    'Featured products': 'Öne çıkan ürünler',
    'Featured products (WooCommerce)': 'Öne çıkan ürünler (WooCommerce)',
    'Featured — %s': 'Öne çıkan — %s',
    'Footer Column %d': 'Footer Kolonu %d',
    'Footer Column 1': 'Footer Kolonu 1',
    'Footer Column 2': 'Footer Kolonu 2',
    'Footer Column 3': 'Footer Kolonu 3',
    'Footer copyright line': 'Footer telif satırı',
    'Footer legal text': 'Footer yasal metni',
    'Full-stack security, one accountable partner.': 'Uçtan uca güvenlik, tek sorumlu iş ortağı.',
    'GNN Demo': 'GNN Demo',
    'GNN Pill': 'GNN Hap Buton',
    'GNN Theme': 'GNN Tema',
    'GNN Slider': 'GNN Slider',
    'Slides shown in the front-page hero. Add as many as you like; drag order follows the list. A slide with an empty title is skipped.':
        'Ön sayfa hero bölümünde görünen slaytlar. İstediğiniz kadar ekleyebilirsiniz; sıralama listedeki düzeni izler. Başlığı boş olan slayt atlanır.',
    'Autoplay': 'Otomatik oynat',
    'Autoplay interval (seconds)': 'Otomatik oynatma aralığı (saniye)',
    'Slide': 'Slayt',
    'Remove slide': 'Slaytı kaldır',
    'Background image (1×)': 'Arka plan görseli (1×)',
    'Background image (2× retina)': 'Arka plan görseli (2× retina)',
    'Kicker': 'Üst başlık',
    'Title': 'Başlık',
    'Text': 'Metin',
    'Button label': 'Düğme etiketi',
    'Button URL': 'Düğme URL’si',
    '+ Add slide': '+ Slayt ekle',
    'Save slider': 'Slaytları kaydet',
    'GNN Display Options': 'GNN Görüntü Seçenekleri',
    'Hide the page title': 'Sayfa başlığını gizle',
    'Hide the breadcrumb (Home / …)': 'İçerik yolunu gizle (Ana Sayfa / …)',
    'GNN Theme Options': 'GNN Tema Seçenekleri',
    'GNN Theme Panel': 'GNN Tema Paneli',
    'Get a Quote': 'Teklif Alın',
    'Go to slide %d': '%d. slayta git',
    'Google Analytics 4 ID': 'Google Analytics 4 kimliği',
    'Google Tag Manager ID': 'Google Tag Manager kimliği',
    'Header': 'Üst Bölüm',
    'Hero Slider': 'Hero Slider',
    'Highlights': 'Öne çıkanlar',
    'Home': 'Ana Sayfa',
    'Install and activate WooCommerce first so the demo products import correctly.':
        'Demo ürünlerin doğru içe aktarılması için önce WooCommerce’i kurup etkinleştirin.',
    'Leave a comment': 'Yorum yazın',
    'Left': 'Sol',
    'Light': 'Açık',
    'Load WooCommerce assets only on shop pages': 'WooCommerce varlıklarını yalnız mağaza sayfalarında yükle',
    'Logo — light mode (1×)': 'Logo — açık mod (1×)',
    'Logo — light mode (2× retina)': 'Logo — açık mod (2× retina)',
    'Logo — dark mode (1×)': 'Logo — koyu mod (1×)',
    'Logo — dark mode (2× retina)': 'Logo — koyu mod (2× retina)',
    'Logo max height (px)': 'Logo en fazla yükseklik (px)',
    'Light mode uses dark artwork; dark mode uses light artwork. Upload a 2× version of each for crisp logos on Retina / high-DPI screens. If you only fill one mode, it is used for both.':
        'Açık mod koyu renk çizimi, koyu mod açık renk çizimi kullanır. Retina / yüksek yoğunluklu ekranlarda net görünmesi için her birinin 2× sürümünü de yükleyin. Yalnız bir modu doldurursanız ikisi için de o kullanılır.',
    'Displayed height; width scales automatically. Upload artwork at 2× this height for sharpness.':
        'Görünen yükseklik; genişlik otomatik ölçeklenir. Netlik için çizimi bu yüksekliğin 2× katında yükleyin.',
    'Mean incident response': 'Ortalama olay müdahalesi',
    'Menu': 'Menü',
    'Mobile': 'Mobil',
    'Mobile Menu': 'Mobil Menü',
    'New': 'Yeni',
    'Newer comments →': 'Yeni yorumlar →',
    'Next slide': 'Sonraki slayt',
    'Next →': 'Sonraki →',
    'No results found': 'Sonuç bulunamadı',
    'No sidebar': 'Kenar çubuğu yok',
    'Not found': 'Bulunamadı',
    'Nothing here yet': 'Henüz içerik yok',
    'Page': 'Sayfa',
    'Page not found': 'Sayfa bulunamadı',
    'Pages using [products] or Woo blocks are detected automatically.':
        '[products] veya Woo blokları kullanan sayfalar otomatik algılanır.',
    'Pages:': 'Sayfalar:',
    'Performance': 'Performans',
    'Placeholders: %year% and %site%. Leave empty for the default.':
        'Yer tutucular: %year% ve %site%. Varsayılan için boş bırakın.',
    'Platform uptime SLA': 'Platform çalışma süresi SLA',
    'Post': 'Yazı',
    'Posts': 'Yazılar',
    'Preload theme fonts': 'Tema fontlarını önden yükle',
    'Previous slide': 'Önceki slayt',
    'Primary': 'Birincil',
    'Primary Menu': 'Birincil Menü',
    'Product': 'Ürün',
    'Products per page': 'Sayfa başına ürün',
    'Raw JS, printed inside a <script> tag in <head>. Requires the unfiltered_html capability.':
        'Ham JS; <head> içinde <script> etiketiyle basılır. unfiltered_html yetkisi gerektirir.',
    'Ready to secure your stack?': 'Altyapınızı güvenceye almaya hazır mısınız?',
    "Remember each visitor's choice (localStorage)": 'Her ziyaretçinin seçimini hatırla (localStorage)',
    'Remove': 'Kaldır',
    'Remove jQuery Migrate (front-end)': 'jQuery Migrate’i kaldır (ön yüz)',
    'Remove oEmbed discovery links': 'oEmbed keşif bağlantılarını kaldır',
    'Right': 'Sağ',
    'Save Settings': 'Ayarları Kaydet',
    'Search': 'Ara',
    'Search for:': 'Şunu ara:',
    'Search products, posts, pages…': 'Ürün, yazı, sayfa arayın…',
    'Select image': 'Görsel seç',
    'Shop columns': 'Mağaza kolon sayısı',
    'Show the cart link (WooCommerce)': 'Sepet bağlantısını göster (WooCommerce)',
    'Show the dark/light toggle in the header': 'Üst bölümde koyu/açık düğmesini göster',
    'Show the search link': 'Arama bağlantısını göster',
    'Shown bottom-right in the footer. Leave empty to hide.':
        'Footer’ın sağ altında görünür. Gizlemek için boş bırakın.',
    'Shown on the front page. Leave a slide title empty to hide that slide.':
        'Ön sayfada görünür. Bir slaytı gizlemek için başlığını boş bırakın.',
    'Sidebar': 'Kenar Çubuğu',
    'Sidebar position': 'Kenar çubuğu konumu',
    'Skip to content': 'İçeriğe geç',
    'Slide %1$d — %2$s': 'Slayt %1$d — %2$s',
    'Slide %d — image': 'Slayt %d — görsel',
    'Slow the Heartbeat API to 60s': 'Heartbeat API’yi 60 sn’ye yavaşlat',
    'Statistics cards': 'İstatistik kartları',
    'Sticky header': 'Sabit üst bölüm',
    'Suggested: #34d399, #22d3ee, #fb923c, #a78bfa': 'Önerilen: #34d399, #22d3ee, #fb923c, #a78bfa',
    'Tag': 'Etiket',
    'The page you’re looking for was moved, renamed or never existed.':
        'Aradığınız sayfa taşınmış, adı değişmiş ya da hiç var olmamış.',
    'Adds the font stylesheet site-wide so .material-symbols-* classes render.':
        'Site genelinde .material-symbols-* sınıflarının çalışması için font stil dosyasını ekler.',
    'Check GitHub for new releases': 'Yeni sürümler için GitHub’u kontrol et',
    'Check for updates now': 'Şimdi güncellemeleri kontrol et',
    'Content bottom spacing (px)': 'İçerik alt boşluğu (px)',
    'Content top spacing (px)': 'İçerik üst boşluğu (px)',
    'Could not reach GitHub to check for updates.': 'Güncellemeler kontrol edilirken GitHub’a ulaşılamadı.',
    'Elementor': 'Elementor',
    'Filled': 'Dolu',
    'Gap between the header and the page content — or between the featured image and the content, when the page has one.':
        'Üst bölüm ile sayfa içeriği arasındaki boşluk — sayfada öne çıkarılan görsel varsa, görsel ile içerik arasındaki boşluk.',
    'Gap between the page content and the footer.': 'Sayfa içeriği ile alt bölüm arasındaki boşluk.',
    'Gutenberg': 'Gutenberg',
    'Fonts by element': 'Öğeye göre yazı tipleri',
    'H1': 'H1',
    'H2': 'H2',
    'H3': 'H3',
    'H4': 'H4',
    'H5': 'H5',
    'H6': 'H6',
    'Paragraph (body text)': 'Paragraf (gövde metni)',
    'Use Google Fonts instead': 'Bunun yerine Google Fonts kullan',
    'Off by default. When on, any element below with a font name set loads that Google Font; elements left empty keep the fast self-hosted default. Every font you pick is combined into a single stylesheet request, never one per font.':
        "Varsayılan olarak kapalıdır. Açıldığında, aşağıda yazı tipi adı girilen her öğe o Google Font'u yükler; boş bırakılan öğeler hızlı, sunucuda barındırılan varsayılanı kullanmaya devam eder. Seçtiğiniz tüm yazı tipleri tek bir stil dosyası isteğinde birleştirilir, asla yazı tipi başına ayrı istek yapılmaz.",
    'The theme ships self-hosted Space Grotesk (headings) and Manrope (body) — fast, and used by default with zero extra requests.':
        'Tema, sunucuda barındırılan Space Grotesk (başlıklar) ve Manrope (gövde) yazı tipleriyle gelir — hızlıdır ve varsayılan olarak ekstra istek yapmadan kullanılır.',
    'Type the exact name from fonts.google.com (e.g. "Poppins", "IBM Plex Sans"). Leave empty to keep the theme default for that element. Turkish characters (ğ ı ş ö ü ç) need no separate setting — Google Fonts and the browser fetch the extended character set automatically, only when the page actually needs it.':
        'fonts.google.com\'daki tam adı yazın (ör. "Poppins", "IBM Plex Sans"). O öğe için tema varsayılanını korumak üzere boş bırakın. Türkçe karakterler (ğ ı ş ö ü ç) için ayrı bir ayar gerekmez — Google Fonts ve tarayıcı, genişletilmiş karakter setini yalnızca sayfa gerçekten ihtiyaç duyduğunda otomatik olarak getirir.',
    'Icon style': 'İkon stili',
    'Installed version: %s': 'Kurulu sürüm: %s',
    'Load Google Material Symbols': 'Google Material Symbols’ı yükle',
    'Outlined': 'Çizgili',
    'Page builder': 'Sayfa oluşturucu',
    'Panel-controlled theme settings — no code required.': 'Panelden yönetilen tema ayarları — kod gerekmez.',
    'Rounded': 'Yuvarlak',
    'Save': 'Kaydet',
    'Sharp': 'Keskin',
    'The theme uses inline SVG icons for its own UI. Google Material Symbols can additionally be loaded for use in page content and menus.':
        'Tema kendi arayüzü için satır içi SVG ikonlar kullanır. Sayfa içeriğinde ve menülerde kullanılmak üzere Google Material Symbols de yüklenebilir.',
    'Theme update settings saved.': 'Tema güncelleme ayarları kaydedildi.',
    'Theme updates (GitHub)': 'Tema güncellemeleri (GitHub)',
    'Check for updates': 'Güncellemeleri kontrol et',
    'Update available: version %s.': 'Güncelleme mevcut: sürüm %s.',
    'Update check complete.': 'Güncelleme kontrolü tamamlandı.',
    'Update now': 'Şimdi güncelle',
    'Update to %s': '%s sürümüne güncelle',
    'The check-for-updates / update button now lives at the top of this panel, under the version number.':
        'Güncelleme kontrolü / güncelleme butonu artık bu panelin en üstünde, sürüm numarasının altında yer alıyor.',
    'Gutenberg only.': 'Sadece Gutenberg.',
    'This slider renders on the default (Gutenberg-driven) front page template only. If the front page has been built or replaced with Elementor — including the "GNN Ana Sayfa" Elementor template — the slider will not appear there, since Elementor content takes over the entire front page.':
        'Bu slider yalnızca varsayılan (Gutenberg tabanlı) ön sayfa şablonunda görüntülenir. Ön sayfa Elementor ile oluşturulmuş veya değiştirilmişse — "GNN Ana Sayfa" Elementor şablonu dahil — slider orada görünmez, çünkü Elementor içeriği tüm ön sayfayı devralır.',
    'Use it in content with e.g. %s': 'İçerikte örneğin şöyle kullanın: %s',
    'You are running the latest version.': 'En güncel sürümü kullanıyorsunuz.',
    'Every theme color lives here. Type a hex code directly, or use the small swatch to pick one visually.':
        'Temanın tüm renkleri burada. Doğrudan hex kod yazabilir ya da küçük renk örneğiyle görsel olarak seçebilirsiniz.',
    'Leave empty to match the theme automatically.': 'Otomatik olarak temayla eşleşmesi için boş bırakın.',
    'Theme default': 'Tema varsayılanı',
    'Top bar colors have moved to the Colors tab, alongside every other theme color.':
        'Üst çubuk renkleri, temanın diğer tüm renkleriyle birlikte Renkler sekmesine taşındı.',
    'Used for buttons, links and highlights across the theme (and the Elementor color palette).':
        'Temadaki butonlar, bağlantılar ve vurgular için kullanılır (ve Elementor renk paletinde).',
    'Blog image alignment': 'Blog görseli hizalaması',
    'Blog image fit': 'Blog görseli sığdırma',
    'Blog image height (px)': 'Blog görseli yüksekliği (px)',
    'Blog: single post pages.': 'Blog: tekil yazı sayfaları.',
    'Bottom': 'Alt',
    'Contain (show the whole image)': 'Sığdır (görselin tamamını göster)',
    'Cover (fill and crop)': 'Kapla (doldur ve kırp)',
    'Featured image': 'Öne çıkarılan görsel',
    'Fill (stretch)': 'Doldur (uzat)',
    'Page image alignment': 'Sayfa görseli hizalaması',
    'Page image fit': 'Sayfa görseli sığdırma',
    'Page image height (px)': 'Sayfa görseli yüksekliği (px)',
    'Pages: Default, Boxed, Left Sidebar and Right Sidebar templates.':
        'Sayfalar: Varsayılan, Kutulu, Sol Kenar Çubuğu ve Sağ Kenar Çubuğu şablonları.',
    'Top': 'Üst',
    'Which part of the image stays visible when it gets cropped.': 'Kırpıldığında görselin hangi kısmının görünür kalacağı.',
    'Hide Breadcrumb': 'Breadcrumb’ı Gizle',
    'Auto-detect (default)': 'Otomatik algıla (varsayılan)',
    'Contact page': 'İletişim sayfası',
    'Used by the mobile dock\'s Contact link (and anywhere else the theme links to "get in touch"). Auto-detect looks for a page slugged "contact" or "iletisim".':
        'Mobil dock’taki İletişim bağlantısı için kullanılır (temanın “bize ulaşın” bağlantısı verdiği her yerde). Otomatik algılama “contact” veya “iletisim” slug’lı bir sayfa arar.',
    'Theme Mode': 'Tema Modu',
    'Toggle dark / light mode': 'Koyu / açık modu değiştir',
    'Trusted by security teams at': 'Güvenlik ekiplerinin tercihi:',
    'Trusted-by logo strip': 'Referans logo şeridi',
    'Try a different search term, or browse the catalog and blog from the menu.':
        'Farklı bir arama terimi deneyin ya da menüden kataloğa ve bloga göz atın.',
    'View all': 'Tümünü gör',
    'Visitors can still toggle; their choice persists in the browser.':
        'Ziyaretçiler yine de değiştirebilir; seçim tarayıcıda saklanır.',
    'Why us': 'Neden biz',
    'Written by': 'Yazan',
    'Your comment is awaiting moderation.': 'Yorumunuz onay bekliyor.',
    'button URL': 'düğme URL’si',
    'button label': 'düğme etiketi',
    'kicker': 'üst başlık',
    'text': 'metin',
    'title': 'başlık',
    '© %1$s %2$s. All rights reserved.': '© %1$s %2$s. Tüm hakları saklıdır.',
    '← Older comments': '← Eski yorumlar',
    '← Prev': '← Önceki',
    '← Previous': '← Önceki',
}
